### ISSUE TITLE
Query with smda report

### ISSUE THREAD

**Issue by malwarefrank** [fkie-cad/mcritweb#28]
The `Query Sample` view has an option for `Unmapped` or `Dumped`.  I would like to request a third option `SMDA` as is supported by the command-line mcrit client query.

I submitted an smda report via the command-line client and was able to view the results in the web interface, so hopefully this is a simple update.

**Comment by danielplohmann** [comment]
Hey!
Let's put it this way: the CLI part only affects the back-end, which is where I feel pretty comfortable. 
Changing the view requires some front-end work involving JavaScript, that's where the dragons live. :laughing: 
But I can relate and also wanted that functionality before so I'll have a look at getting this done (also #20).

**Comment by danielplohmann** [comment]
Alright, in the end I had to patch the Dropzone.js to offer me all data needed to auto-fill the forms with `family`, `version` etc. from the SmdaReport, but this now works.
So I'm happy to report that in mcritweb-1.3.3 you can now submit samples and do query with SmdaReports. :+1: 
I'm waiting with bumping the `mcrit-docker` so that I can directly adopt it with the potential PR that you mentioned so we have one round of testing for free. :)
